### ISSUE TITLE
Error in case when user did not fill last name

### ISSUE THREAD

**Issue by vtsutsman** [SocialiteProviders/Foursquare#1]
In case when user filled only first name, we would get error
.../socialiteproviders/foursquare/src/Provider.php(48): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/home/linefinet...', 48, Array)
#1 .../vendor/laravel/socialite/src/Two/AbstractProvider.php(196): SocialiteProviders\Foursquare\Provider->mapUserToObject(Array)
#2 .../app/Http/Controllers/Auth/SocialController.php(107): Laravel\Socialite\Two\AbstractProvider->user()
#3 [internal function]: App\Http\Controllers\Auth\SocialController->handleProviderCallback('foursquare')
#4 .../bootstrap/cache/compiled.php(8766): call_user_func_array(Array, Array)

**Comment by DraperStudio** [comment]
Fixed with https://github.com/SocialiteProviders/Foursquare/pull/4
